@echo off
setlocal EnableExtensions EnableDelayedExpansion

rem Build the C# WinUI application as a self-contained folder deployment.
set "ROOT=%~dp0"
pushd "%ROOT%" >nul
if errorlevel 1 (
    echo ERROR: Cannot enter the project directory.
    pause
    exit /b 1
)

set "CONFIG=%~1"
if /I "%CONFIG%"=="single" (
    echo ERROR: Single-file deployment has been removed. Use the folder deployment.
    goto :fail
)
if not defined CONFIG set "CONFIG=Release"

if not "%~2"=="" if /I not "%~2"=="folder" (
    echo ERROR: Only folder deployment is supported. Omit the second argument or use folder.
    goto :fail
)

set "SOLUTION=HuorongAce.sln"
set "APP_PROJECT=src\HuorongAce.App\HuorongAce.App.csproj"
rem The solution configuration is Any CPU; its app project maps this to x64.
set "PLATFORM=Any CPU"
set "APP_PLATFORM=x64"
set "TFM=net8.0-windows10.0.19041.0"
set "RID=win-x64"
set "BUILD_OUTPUT_DIR=src\HuorongAce.App\bin\x64\%CONFIG%\%TFM%\%RID%"
set "STAGING_DIR=%ROOT%.publish\HuorongAce-folder"
set "SOURCE_EXE=%STAGING_DIR%\HuorongAce.exe"
set "DIST_ROOT=%ROOT%dist"
set "DIST_DIR=%DIST_ROOT%\HuorongAce-folder"
set "DEST_EXE=%DIST_DIR%\HuorongAce.exe"

where dotnet >nul 2>nul
if errorlevel 1 (
    echo ERROR: dotnet was not found in PATH.
    popd
    pause
    exit /b 1
)

rem WinUI PRI tasks are supplied by Visual Studio Build Tools. Use the
rem documented user-local installation when the environment variable is absent.
if not defined VS_BUILDTOOLS_PATH (
    set "DEFAULT_VS=%USERPROFILE%\.toolchain\vsbuildtools"
    if exist "!DEFAULT_VS!\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage" (
        set "VS_BUILDTOOLS_PATH=!DEFAULT_VS!"
    )
)

rem Keep first-run state in a writable temporary location on restricted machines.
if not defined DOTNET_CLI_HOME set "DOTNET_CLI_HOME=%TEMP%\HuorongAce-dotnet"
if not exist "%DOTNET_CLI_HOME%" mkdir "%DOTNET_CLI_HOME%" >nul 2>nul
set "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1"
set "DOTNET_CLI_TELEMETRY_OPTOUT=1"

if not exist "%DIST_ROOT%" mkdir "%DIST_ROOT%" >nul 2>nul
if not exist "%DIST_ROOT%" (
    echo ERROR: Could not create the distribution directory:
    echo        %DIST_ROOT%
    goto :fail
)

if exist "%DIST_DIR%" (
    echo Cleaning previous folder deployment...
    rmdir /S /Q "%DIST_DIR%"
    if exist "%DIST_DIR%" (
        echo ERROR: Could not clean the previous deployment:
        echo        %DIST_DIR%
        goto :fail
    )
)
mkdir "%DIST_DIR%" >nul 2>nul
if not exist "%DIST_DIR%" (
    echo ERROR: Could not create the deployment directory:
    echo        %DIST_DIR%
    goto :fail
)

if exist "%STAGING_DIR%" rmdir /S /Q "%STAGING_DIR%"
mkdir "%STAGING_DIR%" >nul 2>nul
if not exist "%STAGING_DIR%" (
    echo ERROR: Could not create the publish staging directory:
    echo        %STAGING_DIR%
    goto :fail
)

echo Publishing folder deployment (%CONFIG% ^| %RID%)...
dotnet publish "%ROOT%%APP_PROJECT%" --configuration "%CONFIG%" --runtime "%RID%" --self-contained true --property:Platform="%APP_PLATFORM%" -p:PublishTrimmed=false -p:PublishReadyToRun=false -p:EnableMsixTooling=true -o "%STAGING_DIR%"
if errorlevel 1 (
    echo ERROR: Folder publish failed.
    goto :fail
)

if not exist "%SOURCE_EXE%" (
    echo ERROR: Build succeeded but the executable was not found:
    echo        %SOURCE_EXE%
    goto :fail
)

echo Copying the complete runtime directory...
robocopy "%STAGING_DIR%" "%DIST_DIR%" /E /COPY:DAT /R:2 /W:1 /NFL /NDL /NJH /NJS >nul
if errorlevel 8 (
    echo ERROR: Could not copy the folder deployment.
    goto :fail
)

rem WinUI's PRI/XBF files are generated by the AppX targets but are not always
rem copied by dotnet publish for an unpackaged app. Add them explicitly.
for %%F in (App.xbf SettingsWindow.xbf resources.pri Microsoft.UI.pri Microsoft.UI.Xaml.Controls.pri) do (
    if exist "%BUILD_OUTPUT_DIR%\%%F" copy /Y "%BUILD_OUTPUT_DIR%\%%F" "%DIST_DIR%\%%F" >nul
)

powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%tools\Prune-LocaleResources.ps1" -Root "%DIST_DIR%"
if errorlevel 1 (
    echo ERROR: Could not prune unsupported language resources.
    goto :fail
)
goto :verify

:verify
if not exist "%DEST_EXE%" (
    echo ERROR: The deployment executable was not found:
    echo        %DEST_EXE%
    goto :fail
)

if not exist "%DIST_DIR%\resources.pri" if not exist "%DIST_DIR%\HuorongAce.pri" (
    echo ERROR: Folder deployment is missing the application PRI resource.
    goto :fail
)
if not exist "%DIST_DIR%\App.xbf" (
    echo ERROR: Folder deployment is missing App.xbf.
    goto :fail
)

echo.
echo Build complete.
echo Mode: folder
echo Launch: %DEST_EXE%
popd
if /I not "%CI%"=="1" pause
exit /b 0

:fail
popd
if /I not "%CI%"=="1" pause
exit /b 1
